### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Guymosciski** [cold-try/Gank-RECON#1]
Hi, i found your Gank-Recon is amazing. Could you please add more resources to grab subdomains from like crt.sh, virustotal, otx alienvault, intelx, bevigil. 
Thanks.

**Comment by cold-try** [comment]
Hi, glad you like it.

Yes it is planned, as well as two new features:
- Search for secrets, on all subdomains and their JS files
- Bruteforce of subdomains returning a 401 requiring a basic auth (key-value pair in b64)

I still specify that crt.sh is already implemented, the rest is coming.

**Comment by cold-try** [comment]
It's implemented.
